version: '3.1'

services:
  backend:
    image: 'final-project-iso'
    container_name: 'self-generated-backend-container'
    depends_on:
      - pgdb
    environment:
      - SERVER_PORT=8085
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgdb:5432/postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
    ports:
      - 8009:8085

  pgdb:
    image: 'postgres'
    container_name: 'pg-container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - 2345:5432